### ISSUE TITLE
STA/OPR 9750 Victor-Louie MiniProject #02

### ISSUE THREAD

**Issue by Victor-Louie** [slyastrologer/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've uploaded my work for MiniProject #02 - check it out!

https://victor-louie.github.io/STA9750-2024-FALL/mp02.html

**Comment by michaelweylandt** [comment]
Hi @Victor-Louie, 

Why are you putting this on @slyastrologer's repository instead of your own? I'm a bit confused.

**Comment by Victor-Louie** [comment]
Hi @michaelweylandt

Apologies I thought I was in my own repository. I will sent it again.
